AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with public and private subnets'

Parameters:

      KeyName:
        Description: Select an existing EC2 KeyPair to enable SSH access to the Jenkins instance
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
    
      AvailabilityZone:
        Description: Select the Availability Zone
        Type: AWS::EC2::AvailabilityZone::Name

      ContainerPort:
        Type: Number
        Description: Enter the port on which the container listens (Eg:80)
        MinValue: 1
        MaxValue: 65535
        ConstraintDescription: must be between 1 and 65535.
        Default: 80

      Containerimage:
        Type: String
        Description: Enter the Docker Image ID for the container (Eg:httpd:2.4)
        Default: httpd:2.4

      ClusterName:
        Type: String 
        Description: Enter the Name for Cluster. 
        Default: ECS

      VpcCIDR:
        Description: Please enter the IP range (CIDR notation) for this VPC(Eg:10.192.0.0/16)
        Type: String
        
      PublicSubnetCIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the Availability Zone(Eg:10.192.10.0/24)
        Type: String
        
      PrivateSubnetCIDR:
        Description: Please enter the IP range (CIDR notation) for the private subnet in the Availability Zone(Eg:10.192.12.0/24)
        Type: String

      TaskCpu:
        Description: Enter the number of cpu units used by the task (Eg:512) Refer more combinations on https://docs.aws.amazon.com/AmazonECS/latest/userguide/fargate-task-defs.html#fargate-tasks-size
        Type: Number

      TaskMemory:
        Description: Enter the amount of memory (in GiB) used by the task (Eg:2) Refer more combinations on https://docs.aws.amazon.com/AmazonECS/latest/userguide/fargate-task-defs.html#fargate-tasks-size
        Type: Number

      EmailId: 
        Type: String
        Description: Provide email to receive the alarm notifications for CPU Utilization of ECS Service (This product collects Email ID for the sole purpose of sending alarm notifications internally. It does not store or use for any other purpose.)
      
      AccessCIDR:
        Description: Please set CIDR to x.x.x.x/32 to allow one specific IP address access, 0.0.0.0/0 to allow all IP addresses access, or another CIDR range for application access
        Type: String

Mappings:
    
    RegionMap:
      us-east-1: 
        jenkinsami: ami-03daeb991f5066b16
      us-east-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      us-west-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      us-west-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ca-central-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-central-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-central-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-west-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-west-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-west-3:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-north-1: 
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-south-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      eu-south-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-northeast-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-northeast-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-northeast-3:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-3:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-southeast-4:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-south-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-south-2:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      ap-east-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      sa-east-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      me-central-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      me-south-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
      af-south-1:
        jenkinsami: ami-xxxxxxxxxxxxxxxxx
    
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - ClusterName
          - VpcCIDR
          - PublicSubnetCIDR
          - PrivateSubnetCIDR
          - AvailabilityZone
          - KeyName
          
      - Label:
          default: "Container Configuration"
        Parameters:
          - TaskCpu
          - TaskMemory
          - ContainerPort
          - Containerimage
          - EmailId  
          - AccessCIDR  

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://serverless-wp-testing.s3.amazonaws.com/cfnlint/vpc.yaml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        ClusterName: !Ref ClusterName
        ContainerPort: !Ref ContainerPort
        AccessCIDR: !Ref AccessCIDR
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
        PrivateSubnetCIDR: !Ref PrivateSubnetCIDR
        AvailabilityZone: !Ref AvailabilityZone      

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://serverless-wp-testing.s3.amazonaws.com/cfnlint/efsnodb.yaml
      Parameters:
        PerformanceMode: generalPurpose
        ThroughputMode: bursting
        EfsProvisionedThroughputInMibps: 0
        ClusterName: !Ref ClusterName
        PrivateSubnet: !GetAtt VPC.Outputs.PrivateSubnet
        EFSSecurityGroup: !GetAtt VPC.Outputs.EFSSecurityGroup

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://serverless-wp-testing.s3.amazonaws.com/cfnlint/ecsnodb.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        Containerimage: !Ref Containerimage
        MinCapacity: 1
        MaxCapacity: 50
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        ContainerPort: !Ref ContainerPort
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnet: !GetAtt VPC.Outputs.PublicSubnet
        PrivateSubnet: !GetAtt VPC.Outputs.PrivateSubnet
        FileSystemId: !GetAtt EFS.Outputs.FileSystemId
        AccessPointId: !GetAtt EFS.Outputs.AccessPointId  
        ECSTaskRole: !GetAtt EFS.Outputs.TaskRole 
        ContainerSecurityGroup: !GetAtt VPC.Outputs.ContainerSecurityGroup

  Monitoring:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://serverless-wp-testing.s3.amazonaws.com/cfnlint/monitoring.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        ServiceName: !GetAtt Cluster.Outputs.service
        CPUAlarmThreshold: 75
        EmailId: !Ref EmailId


  Jenkins:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://serverless-wp-testing.s3.amazonaws.com/cfnlint/jenkins.yaml
      Parameters:
        InstanceName: Jenkins
        InstanceType: t3.large
        KeyName: !Ref KeyName
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnet: !GetAtt VPC.Outputs.PublicSubnet
        Jenkinsami: !FindInMap [RegionMap, !Ref "AWS::Region", jenkinsami]
        AccessCIDR: !Ref AccessCIDR
           
        
Outputs:
     Endpoint:
      Description: "Loadbalancer endpoint"
      Value: 
       !GetAtt Cluster.Outputs.Endpoint

     PublicIP:
      Description: "Public IP address of the created Jenkins EC2 instance"
      Value: 
       !GetAtt Jenkins.Outputs.PublicIP